[
  ./out.nix
  ./misc/extra-arguments.nix
  ./virtualisation/containers.nix
  ./config/swap.nix
  ./tasks/network-interfaces.nix
  ./misc/ids.nix
  ./system/boot/loader/efi.nix
  ./misc/label.nix
  ./misc/version.nix
  ./system/boot/stage-2.nix
  ./programs/shadow.nix
  ./programs/bash/bash.nix
  ./services/x11/xserver.nix
  ./services/system/nscd.nix
  ./security/google_oslogin.nix
  ./system/boot/resolved.nix
  ./config/fonts/fontconfig-penultimate.nix
  ./services/misc/sssd.nix
  ./config/ldap.nix
  ./services/network-filesystems/samba.nix
  ./services/logging/rsyslogd.nix
  ./services/logging/syslog-ng.nix
  ./config/krb5/default.nix
  ./security/oath.nix
  ./services/networking/wpa_supplicant.nix
  ./services/misc/nix-daemon.nix
  ./services/security/fprintd.nix
  ./security/pam_usb.nix
  ./security/pam_mount.nix
  ./virtualisation/lxcfs.nix
  ./hardware/device-tree.nix
  ./config/resolvconf.nix
  ./config/i18n.nix
  ./system/boot/loader/loader.nix
]
